// projectM Android TV - native engine
//
// Threading model
// ---------------
// * GL thread   : everything that touches the projectM handle (create, render, load presets,
//                 settings). projectM compiles shaders while loading presets, so preset switches
//                 MUST happen on the thread that owns the EGL context.
// * Any thread  : commands (next/previous/random), settings and audio are written into atomics /
//                 mutex-protected buffers and picked up by the GL thread at the start of the next
//                 frame. Java never needs to queueEvent() for correctness.
// * Worker      : a single background thread indexes the preset list from the APK assets and
//                 prefetches (reads + decompresses) the next preset so the GL thread only has to
//                 parse/compile it.
//
// Presets are read straight from the APK via AAssetManager, so nothing is extracted to disk.
//
// Transitions
// -----------
// Classic: projectM's soft cut renders the outgoing and incoming preset for the whole transition
// (double CPU and GPU cost, two presets' buffers in memory). Lightweight: projectM hard-cuts (the
// new preset still starts from the old image) and SnapshotFade fades a still copy of the last
// frame out over it, which costs one textured pass per frame. Auto starts lightweight on low-end
// or low-memory devices and switches to lightweight when a classic blend runs visibly slower.

#include <jni.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/log.h>
#include <GLES3/gl3.h>
#include <sys/stat.h>
#include <sys/system_properties.h>
#include <unistd.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdio>
#include <cctype>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <functional>
#include <mutex>
#include <random>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include "projectM-4/projectM.h"
#include "snapshot_fade.h"

#define LOG_TAG "projectM-Native"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace {

constexpr const char* kPresetDir = "presets";
constexpr const char* kPresetIndex = "presets.idx";  // generated by tools/gen-preset-index.py
constexpr const char* kTextureDir = "textures";
constexpr size_t kMaxHistory = 128;
constexpr int kMaxLoadAttemptsPerFrame = 4;

double NowSeconds() {
    using namespace std::chrono;
    return duration<double>(steady_clock::now().time_since_epoch()).count();
}

bool EndsWithMilk(const char* name) {
    size_t len = strlen(name);
    if (len < 5) return false;
    const char* ext = name + len - 5;
    return strncasecmp(ext, ".milk", 5) == 0;
}

// ------------------------------------------------------------------------------------------------
// Preset library: index, shuffle order, history, skip list and background prefetch.
// All public methods are thread-safe.
// ------------------------------------------------------------------------------------------------
class PresetLibrary {
public:
    void Start(AAssetManager* assets, std::string skipFilePath, std::string textureDir) {
        bool expected = false;
        if (!started_.compare_exchange_strong(expected, true)) return;
        assets_ = assets;
        skipFilePath_ = std::move(skipFilePath);
        strikeFilePath_ = skipFilePath_ + ".blank";
        textureDir_ = std::move(textureDir);
        std::thread(&PresetLibrary::WorkerLoop, this).detach();
    }

    bool Ready() const { return ready_.load(std::memory_order_acquire); }

    // Folder with the extracted texture pack (valid once Ready()).
    const std::string& TextureDir() const { return textureDir_; }

    int ActiveCount() {
        std::lock_guard<std::mutex> lock(mutex_);
        return static_cast<int>(order_.size() - std::min(order_.size(), skippedInOrder_));
    }

    int SkippedCount() {
        std::lock_guard<std::mutex> lock(mutex_);
        return static_cast<int>(skipped_.size());
    }

    // Advances the shuffled cursor and returns the next playable preset ("" if none).
    std::string Next() {
        std::lock_guard<std::mutex> lock(mutex_);
        std::string name = PeekNextLocked(true);
        RequestPrefetchLocked();
        return name;
    }

    // Estimated extra memory of a preset in MB (images, random images, complex shaders), from
    // presets.idx; 0 when unknown. Logged with each load to calibrate the estimate.
    int Weight(const std::string& name) {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = weights_.find(name);
        return it == weights_.end() ? 0 : it->second;
    }

    std::string Random(const std::string& avoid) {
        std::lock_guard<std::mutex> lock(mutex_);
        if (order_.empty()) return {};
        std::uniform_int_distribution<size_t> dist(0, order_.size() - 1);
        for (int i = 0; i < 32; ++i) {
            const std::string& candidate = order_[dist(rng_)];
            if (candidate != avoid && !skipped_.count(candidate)) return candidate;
        }
        return PeekNextLocked(true);
    }

    // Returns the preset shown before the current one ("" if there is no history).
    std::string Previous() {
        std::lock_guard<std::mutex> lock(mutex_);
        while (history_.size() >= 2) {
            history_.pop_back();  // current
            std::string candidate = history_.back();
            if (!skipped_.count(candidate)) {
                history_.pop_back();  // will be pushed again when it is shown
                return candidate;
            }
        }
        return {};
    }

    void RecordShown(const std::string& name) {
        std::lock_guard<std::mutex> lock(mutex_);
        history_.push_back(name);
        if (history_.size() > kMaxHistory) history_.pop_front();
    }

    void MarkSkipped(const std::string& name, const char* reason) {
        if (name.empty()) return;
        std::lock_guard<std::mutex> lock(mutex_);
        if (!skipped_.insert(name).second) return;
        ++skippedInOrder_;
        LOGW("SKIP preset='%s' reason=%s", name.c_str(), reason);
        FILE* f = fopen(skipFilePath_.c_str(), "a");
        if (f) {
            fprintf(f, "%s\n", name.c_str());
            fclose(f);
        }
    }

    // Records that `name` rendered black while music played; returns how often that happened so
    // far (persisted, so a preset shown again in a later session counts too).
    int AddBlankStrike(const std::string& name) {
        if (name.empty()) return 0;
        std::lock_guard<std::mutex> lock(mutex_);
        int strikes = ++blankStrikes_[name];
        if (FILE* f = fopen(strikeFilePath_.c_str(), "a")) {
            fprintf(f, "%s\n", name.c_str());
            fclose(f);
        }
        return strikes;
    }

    void ResetSkipped() {
        std::lock_guard<std::mutex> lock(mutex_);
        skipped_.clear();
        skippedInOrder_ = 0;
        blankStrikes_.clear();
        if (FILE* f = fopen(strikeFilePath_.c_str(), "w")) fclose(f);
        FILE* f = fopen(skipFilePath_.c_str(), "w");
        if (f) fclose(f);
        LOGI("Skip list cleared");
    }

    // Returns the preset file contents, using the prefetched copy when available.
    std::string Load(const std::string& name) {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            if (prefetchedName_ == name) {
                prefetchedName_.clear();
                return std::move(prefetchedData_);
            }
        }
        return ReadAsset(name);
    }

private:
    std::string ReadAsset(const std::string& name) const {
        std::string path = std::string(kPresetDir) + "/" + name;
        AAsset* asset = AAssetManager_open(assets_, path.c_str(), AASSET_MODE_BUFFER);
        if (!asset) {
            LOGE("Unable to open asset %s", path.c_str());
            return {};
        }
        std::string data;
        const void* buffer = AAsset_getBuffer(asset);
        off_t length = AAsset_getLength(asset);
        if (buffer && length > 0) data.assign(static_cast<const char*>(buffer), length);
        AAsset_close(asset);
        return data;
    }

    std::string PeekNextLocked(bool advance) {
        if (order_.empty()) return {};
        // The preset on screen is not picked again (after a reshuffle it can come first), unless
        // it is the only playable one.
        const std::string* shown = history_.empty() ? nullptr : &history_.back();
        bool shownPlayable = false;
        size_t cursor = cursor_;
        for (size_t i = 0; i < order_.size(); ++i) {
            if (cursor >= order_.size()) {
                cursor = 0;
                if (advance) std::shuffle(order_.begin(), order_.end(), rng_);
            }
            const std::string& candidate = order_[cursor++];
            if (skipped_.count(candidate)) continue;
            if (shown && candidate == *shown) {
                shownPlayable = true;
                continue;
            }
            if (advance) cursor_ = cursor;
            return candidate;
        }
        return shownPlayable ? *shown : std::string();
    }

    void RequestPrefetchLocked() {
        prefetchWanted_ = true;
        cv_.notify_one();
    }

    // projectM only scans real directories for textures, so the bundled texture pack is copied
    // from the APK once (files whose size already matches are skipped on later launches).
    void ExtractTextures() {
        if (textureDir_.empty()) return;
        double start = NowSeconds();
        mkdir(textureDir_.c_str(), 0700);
        AAssetDir* dir = AAssetManager_openDir(assets_, kTextureDir);
        if (!dir) return;
        int copied = 0, total = 0;
        while (const char* file = AAssetDir_getNextFileName(dir)) {
            ++total;
            std::string assetPath = std::string(kTextureDir) + "/" + file;
            std::string target = textureDir_ + "/" + file;
            AAsset* asset = AAssetManager_open(assets_, assetPath.c_str(), AASSET_MODE_BUFFER);
            if (!asset) continue;
            off_t length = AAsset_getLength(asset);
            struct stat st;
            if (stat(target.c_str(), &st) == 0 && st.st_size == length) {
                AAsset_close(asset);
                continue;
            }
            const void* data = AAsset_getBuffer(asset);
            std::string temp = target + ".tmp";
            if (FILE* f = fopen(temp.c_str(), "wb")) {
                bool ok = data && fwrite(data, 1, length, f) == static_cast<size_t>(length);
                ok = (fclose(f) == 0) && ok;
                if (ok && rename(temp.c_str(), target.c_str()) == 0) ++copied;
                else remove(temp.c_str());
            }
            AAsset_close(asset);
        }
        AAssetDir_close(dir);
        LOGI("Textures ready: %d files (%d copied) in %.0f ms", total, copied, (NowSeconds() - start) * 1000.0);
    }

    void WorkerLoop() {
        ExtractTextures();
        BuildIndex();
        std::unique_lock<std::mutex> lock(mutex_);
        for (;;) {
            cv_.wait(lock, [this] { return prefetchWanted_; });
            prefetchWanted_ = false;
            std::string name = PeekNextLocked(false);
            if (name.empty() || name == prefetchedName_) continue;
            lock.unlock();
            std::string data = ReadAsset(name);
            lock.lock();
            prefetchedName_ = name;
            prefetchedData_ = std::move(data);
        }
    }

    void BuildIndex() {
        double start = NowSeconds();
        std::vector<std::string> names;
        names.reserve(10000);
        const char* source = kPresetIndex;
        std::unordered_map<std::string, int> weights;
        if (!ReadIndexFile(names, weights)) {
            // Listing ~10k assets takes seconds on TV boxes and holds the asset-manager lock.
            source = "directory listing";
            AAssetDir* dir = AAssetManager_openDir(assets_, kPresetDir);
            if (dir) {
                while (const char* file = AAssetDir_getNextFileName(dir)) {
                    if (EndsWithMilk(file)) names.emplace_back(file);
                }
                AAssetDir_close(dir);
            }
        }

        std::unordered_set<std::string> skipped;
        if (FILE* f = fopen(skipFilePath_.c_str(), "r")) {
            char line[1024];
            while (fgets(line, sizeof(line), f)) {
                size_t len = strcspn(line, "\r\n");
                line[len] = '\0';
                if (len > 0) skipped.insert(line);
            }
            fclose(f);
        }
        std::unordered_map<std::string, int> strikes;
        if (FILE* f = fopen(strikeFilePath_.c_str(), "r")) {
            char line[1024];
            while (fgets(line, sizeof(line), f)) {
                size_t len = strcspn(line, "\r\n");
                line[len] = '\0';
                if (len > 0) ++strikes[line];
            }
            fclose(f);
        }

        std::lock_guard<std::mutex> lock(mutex_);
        rng_.seed(std::random_device{}());
        std::shuffle(names.begin(), names.end(), rng_);
        order_ = std::move(names);
        weights_ = std::move(weights);
        skipped_ = std::move(skipped);
        blankStrikes_ = std::move(strikes);
        skippedInOrder_ = 0;
        for (const auto& n : order_) skippedInOrder_ += skipped_.count(n);
        cursor_ = 0;
        ready_.store(true, std::memory_order_release);
        prefetchWanted_ = true;  // warm up the first preset
        LOGI("Indexed %zu presets (%zu skipped) in %.0f ms from %s", order_.size(), skippedInOrder_,
             (NowSeconds() - start) * 1000.0, source);
    }

    // Reads the prebuilt preset list: "<file name>[\t<weight MB>]" per line. False if it is
    // missing or empty.
    bool ReadIndexFile(std::vector<std::string>& names, std::unordered_map<std::string, int>& weights) const {
        AAsset* asset = AAssetManager_open(assets_, kPresetIndex, AASSET_MODE_BUFFER);
        if (!asset) return false;
        const char* data = static_cast<const char*>(AAsset_getBuffer(asset));
        size_t length = static_cast<size_t>(std::max<off_t>(0, AAsset_getLength(asset)));
        size_t lineStart = 0;
        for (size_t i = 0; data && i <= length; ++i) {
            if (i < length && data[i] != '\n') continue;
            std::string line(data + lineStart, i - lineStart);
            lineStart = i + 1;
            if (!line.empty() && line.back() == '\r') line.pop_back();
            size_t tab = line.find('\t');
            int weight = 0;
            if (tab != std::string::npos) {
                weight = std::max(0, atoi(line.c_str() + tab + 1));
                line.resize(tab);
            }
            if (!EndsWithMilk(line.c_str())) continue;
            if (weight > 0) weights[line] = weight;
            names.push_back(std::move(line));
        }
        AAsset_close(asset);
        return !names.empty();
    }

    std::atomic<bool> started_{false};
    std::atomic<bool> ready_{false};
    AAssetManager* assets_ = nullptr;
    std::string skipFilePath_;
    std::string strikeFilePath_;  // one line per black verdict
    std::string textureDir_;

    std::mutex mutex_;
    std::condition_variable cv_;
    std::mt19937 rng_;
    std::vector<std::string> order_;
    size_t cursor_ = 0;
    std::deque<std::string> history_;
    std::unordered_set<std::string> skipped_;
    std::unordered_map<std::string, int> blankStrikes_;
    std::unordered_map<std::string, int> weights_;
    size_t skippedInOrder_ = 0;
    bool prefetchWanted_ = false;
    std::string prefetchedName_;
    std::string prefetchedData_;
};

// ------------------------------------------------------------------------------------------------
// Measures what a preset shows while music is playing. Samples 5 rows and 5 columns of the window
// once per second for 20 s after the transition (asynchronous GPU readback) and logs one OUTPUT
// line per preset:
//   * black: every channel <= 20;
//   * flat: the luma range across all sampled pixels is <= 12 (one colour, e.g. all white);
//   * still: compared with the sample 1 s earlier, fewer than 2% of the sampled pixels changed
//     visibly and no region reached 10%. A pixel changed visibly when its luma moved >= 8/255, or
//     its hue moved >= 12 degrees while saturated (S >= 0.2, luma >= 16). Regions are quarters of
//     each sampled line, so a small shape that really moves registers.
// Only black acts (5 black samples in a row with music), and only when "Skip blank presets" is on
// (the default since 1.9.4): the app moves on to the next preset at once, and a preset that is
// black a second time, in any later showing, goes on the skip list. Two strikes keep a one-off
// (music starting late, a slow build-up) from removing a preset for good. Flat and still are only
// measured until real runs show which thresholds are safe.
// ------------------------------------------------------------------------------------------------
class OutputDetector {
public:
    void Arm(double now, double settleSeconds, const std::string& preset) {
        Flush();
        DropPending();
        active_ = true;
        preset_ = preset;
        nextSampleAt_ = now + settleSeconds;
        deadline_ = nextSampleAt_ + kEvaluationWindow;
        badSamples_ = 0;
        stats_ = Stats();
        previous_.clear();
    }

    void Disarm() {
        Flush();
        DropPending();
        active_ = false;
    }

    // True once since the last call if a sample showed visible output (not black).
    bool TakeVisible() {
        bool seen = visibleSeen_;
        visibleSeen_ = false;
        return seen;
    }

    // Frees the readback buffer; the GL context must be current.
    void Release() {
        Disarm();
        if (pbo_) glDeleteBuffers(1, &pbo_);
        pbo_ = 0;
        pboBytes_ = 0;
    }

    // The GL context is gone: forget object names without deleting them.
    void Forget() {
        fence_ = nullptr;
        pending_ = false;
        pbo_ = 0;
        pboBytes_ = 0;
        Disarm();
    }

    // Call once per frame. Returns the reason when the preset has been black for 5 samples in a
    // row, else null; the caller decides whether to act on it.
    const char* Update(double now, int width, int height, bool audioPresent) {
        if (!active_) return nullptr;
        const char* reason = pending_ ? Collect() : nullptr;
        if (!active_ || now < nextSampleAt_) return reason;
        if (now > deadline_) {
            Disarm();
            return reason;
        }
        nextSampleAt_ = now + kSampleInterval;
        // Silence legitimately makes many presets dark or still, and a preset that draws from the
        // music starts from black when the music only just arrived (on a SHIELD the player's audio
        // is found seconds after launch): only samples after kAudioSettle seconds of continuous
        // music count. A read still in flight is not doubled up.
        if (!audioPresent) {
            audioSince_ = -1;
            badSamples_ = 0;
            return reason;
        }
        if (audioSince_ < 0) audioSince_ = now;
        if (now - audioSince_ < kAudioSettle || pending_ || width <= 0 || height <= 0) return reason;
        Issue(width, height);
        return reason;
    }

private:
    // Reads 5 rows and 5 columns of the window (not projectM's internal buffers) into a pixel
    // pack buffer. The copy runs on the GPU; Collect() picks it up once its fence has signalled,
    // so the render thread never waits for the GPU.
    void Issue(int width, int height) {
        GLint readFbo = 0, packBuffer = 0, packAlignment = 4;
        glGetIntegerv(GL_READ_FRAMEBUFFER_BINDING, &readFbo);
        glGetIntegerv(GL_PIXEL_PACK_BUFFER_BINDING, &packBuffer);
        glGetIntegerv(GL_PACK_ALIGNMENT, &packAlignment);
        size_t bytes = static_cast<size_t>(kLines) * (width + height) * 4;
        if (!pbo_) glGenBuffers(1, &pbo_);
        glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_);
        if (bytes != pboBytes_) {
            glBufferData(GL_PIXEL_PACK_BUFFER, static_cast<GLsizeiptr>(bytes), nullptr, GL_STREAM_READ);
            pboBytes_ = bytes;
        }
        glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
        glPixelStorei(GL_PACK_ALIGNMENT, 4);
        size_t offset = 0;
        for (int i = 1; i <= kLines; ++i) {
            glReadPixels(0, height * i / (kLines + 1), width, 1, GL_RGBA, GL_UNSIGNED_BYTE,
                         reinterpret_cast<void*>(offset));
            offset += static_cast<size_t>(width) * 4;
            glReadPixels(width * i / (kLines + 1), 0, 1, height, GL_RGBA, GL_UNSIGNED_BYTE,
                         reinterpret_cast<void*>(offset));
            offset += static_cast<size_t>(height) * 4;
        }
        fence_ = glFenceSync(GL_SYNC_GPU_COMMANDS_COMPLETE, 0);
        glFlush();
        pending_ = fence_ != nullptr;
        pendingWidth_ = width;
        pendingHeight_ = height;
        glPixelStorei(GL_PACK_ALIGNMENT, packAlignment);
        glBindFramebuffer(GL_READ_FRAMEBUFFER, static_cast<GLuint>(readFbo));
        glBindBuffer(GL_PIXEL_PACK_BUFFER, static_cast<GLuint>(packBuffer));
    }

    void DropPending() {
        if (fence_) glDeleteSync(fence_);
        fence_ = nullptr;
        pending_ = false;
    }

    // Evaluates the last read once the GPU has finished it (checked without waiting).
    const char* Collect() {
        GLenum state = glClientWaitSync(fence_, 0, 0);
        if (state == GL_TIMEOUT_EXPIRED) return nullptr;
        DropPending();
        if (state == GL_WAIT_FAILED) return nullptr;

        GLint packBuffer = 0;
        glGetIntegerv(GL_PIXEL_PACK_BUFFER_BINDING, &packBuffer);
        glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_);
        const auto* data = static_cast<const uint8_t*>(
            glMapBufferRange(GL_PIXEL_PACK_BUFFER, 0, static_cast<GLsizeiptr>(pboBytes_), GL_MAP_READ_BIT));
        bool ok = data != nullptr;
        if (ok) {
            current_.clear();
            regionEnds_.clear();
            size_t offset = 0;
            for (int i = 1; i <= kLines; ++i) {
                Keep(data + offset, pendingWidth_);
                offset += static_cast<size_t>(pendingWidth_) * 4;
                Keep(data + offset, pendingHeight_);
                offset += static_cast<size_t>(pendingHeight_) * 4;
            }
            glUnmapBuffer(GL_PIXEL_PACK_BUFFER);
        }
        glBindBuffer(GL_PIXEL_PACK_BUFFER, static_cast<GLuint>(packBuffer));
        return ok ? Evaluate() : nullptr;
    }

    const char* Evaluate() {
        Measure();
        bool flat = lumaRange_ <= kFlatLumaRange;
        if (flat) ++stats_.flatSamples;
        const char* reason = IsBlack() ? "renders no visible output" : nullptr;
        previous_.swap(current_);
        if (!reason) {
            visibleSeen_ = true;
            badSamples_ = 0;
            return nullptr;
        }
        if (++badSamples_ < kRequiredBadSamples) return nullptr;
        stats_.skipped = reason;
        Disarm();
        return reason;
    }

    struct Stats {
        int samples = 0;
        int compared = 0;
        int minLumaRange = 255;
        int maxLumaRange = 0;
        float minChangePct = 100.f;
        float sumChangePct = 0.f;
        float minRegionPct = 100.f;  // lowest per-sample "most active line" share
        long lumaChanges = 0;
        long hueOnlyChanges = 0;
        int flatSamples = 0;
        int stillSamples = 0;        // below both motion thresholds
        const char* skipped = nullptr;
    };

    static constexpr double kSampleInterval = 1.0;
    static constexpr double kEvaluationWindow = 20.0;
    static constexpr double kAudioSettle = 3.0;   // seconds of music before samples count
    static constexpr int kRequiredBadSamples = 5;
    static constexpr int kLines = 5;              // rows and columns each
    static constexpr int kRegionsPerLine = 4;
    static constexpr int kPixelStep = 4;
    static constexpr uint8_t kMaxBlackChannel = 20;  // ~8% brightness
    static constexpr int kFlatLumaRange = 12;
    static constexpr int kLumaDelta = 8;
    static constexpr float kHueDelta = 12.f;      // degrees
    static constexpr float kMinSaturation = 0.2f;
    static constexpr int kMinHueLuma = 16;
    static constexpr float kStillFramePct = 2.f;
    static constexpr float kStillRegionPct = 10.f;

    // Keeps every 4th pixel (RGB) of one read line, split into kRegionsPerLine regions.
    void Keep(const uint8_t* line, int pixels) {
        for (int r = 0; r < kRegionsPerLine; ++r) {
            int from = pixels * r / kRegionsPerLine, to = pixels * (r + 1) / kRegionsPerLine;
            for (int p = from - from % kPixelStep; p < to; p += kPixelStep) {
                if (p < from) continue;
                const uint8_t* px = line + static_cast<size_t>(p) * 4;
                current_.insert(current_.end(), px, px + 3);
            }
            regionEnds_.push_back(current_.size() / 3);
        }
    }

    static int Luma(const uint8_t* px) { return (77 * px[0] + 150 * px[1] + 29 * px[2]) >> 8; }

    // Hue in degrees, or -1 when the pixel is too grey or too dark for hue to mean anything.
    static float Hue(const uint8_t* px) {
        int r = px[0], g = px[1], b = px[2];
        int hi = std::max(r, std::max(g, b)), lo = std::min(r, std::min(g, b));
        if (hi == 0 || Luma(px) < kMinHueLuma || (hi - lo) < kMinSaturation * hi) return -1.f;
        float d = static_cast<float>(hi - lo);
        float h = hi == r ? (g - b) / d : hi == g ? 2.f + (b - r) / d : 4.f + (r - g) / d;
        h *= 60.f;
        return h < 0 ? h + 360.f : h;
    }

    void Measure() {
        size_t pixels = current_.size() / 3;
        int lo = 255, hi = 0;
        for (size_t i = 0; i < pixels; ++i) {
            int y = Luma(&current_[i * 3]);
            lo = std::min(lo, y);
            hi = std::max(hi, y);
        }
        lumaRange_ = pixels ? hi - lo : 0;
        ++stats_.samples;
        stats_.minLumaRange = std::min(stats_.minLumaRange, lumaRange_);
        stats_.maxLumaRange = std::max(stats_.maxLumaRange, lumaRange_);
        still_ = false;
        if (previous_.size() != current_.size() || pixels == 0) return;

        size_t changed = 0, regionStart = 0, region = 0, regionChanged = 0;
        float bestRegionPct = 0.f;
        for (size_t i = 0; i < pixels; ++i) {
            const uint8_t* now = &current_[i * 3];
            const uint8_t* before = &previous_[i * 3];
            bool lumaMoved = std::abs(Luma(now) - Luma(before)) >= kLumaDelta;
            bool hueMoved = false;
            if (!lumaMoved) {
                float h1 = Hue(now), h0 = Hue(before);
                if (h1 >= 0 && h0 >= 0) {
                    float dh = std::fabs(h1 - h0);
                    hueMoved = std::min(dh, 360.f - dh) >= kHueDelta;
                }
            }
            if (lumaMoved) ++stats_.lumaChanges;
            if (hueMoved) ++stats_.hueOnlyChanges;
            if (lumaMoved || hueMoved) {
                ++changed;
                ++regionChanged;
            }
                while (region < regionEnds_.size() && i + 1 == regionEnds_[region]) {
                size_t n = regionEnds_[region] - regionStart;
                if (n) bestRegionPct = std::max(bestRegionPct, 100.f * regionChanged / n);
                regionStart = regionEnds_[region];
                regionChanged = 0;
                ++region;
            }
        }
        float changePct = 100.f * changed / pixels;
        ++stats_.compared;
        stats_.minChangePct = std::min(stats_.minChangePct, changePct);
        stats_.sumChangePct += changePct;
        stats_.minRegionPct = std::min(stats_.minRegionPct, bestRegionPct);
        still_ = changePct < kStillFramePct && bestRegionPct < kStillRegionPct;
        if (still_) ++stats_.stillSamples;
    }

    bool IsBlack() const {
        for (uint8_t c : current_) {
            if (c > kMaxBlackChannel) return false;
        }
        return !current_.empty();
    }

    // One machine-readable line per evaluated preset (tools/tv-diagnostics.sh summarises them).
    void Flush() {
        if (!active_ || stats_.samples == 0) {
            stats_ = Stats();
            return;
        }
        const Stats& s = stats_;
        bool compared = s.compared > 0;
        LOGI("OUTPUT preset='%s' samples=%d luma_range=%d..%d change_pct_min=%.1f change_pct_avg=%.1f "
             "region_pct_min=%.1f luma_changes=%ld hue_only_changes=%ld flat=%d/%d still=%d/%d skipped=%s",
             preset_.c_str(), s.samples, s.minLumaRange, s.maxLumaRange, compared ? s.minChangePct : 0.f,
             compared ? s.sumChangePct / s.compared : 0.f, compared ? s.minRegionPct : 0.f, s.lumaChanges,
             s.hueOnlyChanges, s.flatSamples, s.samples, s.stillSamples, s.compared, s.skipped ? s.skipped : "no");
        stats_ = Stats();
    }

    bool active_ = false;
    std::string preset_;
    double nextSampleAt_ = 0;
    double deadline_ = 0;
    int badSamples_ = 0;
    bool visibleSeen_ = false;
    double audioSince_ = -1;     // when the current run of music started, -1 during silence
    int lumaRange_ = 0;
    bool still_ = false;
    Stats stats_;
    GLuint pbo_ = 0;
    size_t pboBytes_ = 0;
    GLsync fence_ = nullptr;
    bool pending_ = false;
    int pendingWidth_ = 0;
    int pendingHeight_ = 0;
    std::vector<uint8_t> current_;   // RGB of the sampled pixels
    std::vector<uint8_t> previous_;
    std::vector<size_t> regionEnds_;  // pixel index where each sampled line ends
};

// ------------------------------------------------------------------------------------------------
// Cross-thread inputs (written from UI / audio threads, consumed on the GL thread).
// ------------------------------------------------------------------------------------------------
enum Command : int { kNone = 0, kNext, kPrevious, kRandom, kSkipCurrent };
enum TransitionMode : int { kTransitionAuto = 0, kTransitionLightweight = 1, kTransitionClassic = 2 };

constexpr int kBlankStrikesToSkip = 2;          // black verdicts before a preset is skipped for good
// More black presets in a row than this points at our rendering (driver, readback), not at the
// presets: then nothing is struck or skipped until a preset shows visible output again.
constexpr int kMaxBlankInARow = 3;
constexpr double kMaxLightweightSeconds = 3.0;  // a still frame should not linger longer
constexpr float kSlowBlendRatio = 0.8f;         // classic blend slower than this: Auto goes lightweight

struct Inputs {
    std::atomic<int> command{kNone};
    std::atomic<bool> commandHardCut{true};
    std::atomic<bool> forceHardCut{false};  // next automatic switch must be a hard cut
    std::atomic<bool> blankDetection{false};  // act on black presets (always measured)
    std::atomic<int> transitionMode{kTransitionAuto};
    std::atomic<bool> autoLightweight{false};  // Auto's current choice

    std::atomic<int> presetDuration{30};
    std::atomic<int> softCutDuration{7};
    std::atomic<bool> autoChange{true};
    std::atomic<int> meshWidth{48};
    std::atomic<int> meshHeight{32};
    std::atomic<bool> settingsDirty{true};

    std::mutex pcmMutex;
    std::vector<uint8_t> pcm;
    std::atomic<float> audioLevel{0.f};
    std::atomic<double> audioLevelTime{0.0};
};

// Published state, read from any thread.
struct Published {
    std::mutex mutex;
    std::string currentPreset;
    std::atomic<int> changeCounter{0};
    std::atomic<float> lastTransitionFps{0.f};
    std::atomic<int> transitionCounter{0};
};

// GL-thread-only state.
struct Engine {
    projectm_handle pm = nullptr;
    int width = 0;
    int height = 0;
    std::string current;         // preset currently shown
    std::string loading;         // preset being loaded (for failure attribution)
    bool loadFailed = false;
    bool switchRequested = false;
    bool switchHardCut = false;
    OutputDetector detector;
    int blankInARow = 0;         // black verdicts since the last preset with visible output
    SnapshotFade fade;
    bool snapshotReady = false;  // outgoing frame captured for the upcoming automatic switch
    std::vector<uint8_t> pcmScratch;
    int framesSinceFps = 0;
    double fpsWindowStart = 0;
    int appliedMeshWidth = 0;
    int appliedMeshHeight = 0;
    double createdAt = 0;
    bool firstPresetLogged = false;
    bool texturesApplied = false;
    double lastFrameAt = 0;
    float lastFps = 0;
    double lastLoadStart = 0;
    double lastLoadEnd = 0;
    double lastLoadMs = 0;
    // Current transition, measured from the start of the preset load until the blend ends.
    bool inTransition = false;
    bool transitionLightweight = false;
    double transitionStart = 0;
    double transitionLoadEnd = 0;
    double transitionEnd = 0;
    float fpsBeforeTransition = 0;
    int transitionFrames = 0;
    int transitionSlowFrames = 0;
    double transitionWorstMs = 0;
};

// Intentionally never destroyed: its detached worker thread lives as long as the process.
PresetLibrary& g_library = *new PresetLibrary();
Inputs g_inputs;
Published g_published;
Engine g_engine;
std::mutex g_engineMutex;  // guards g_engine against create/destroy races across Activities
jobject g_assetManagerRef = nullptr;

constexpr float kAudioPresentLevel = 0.02f;  // RMS of normalized 8-bit PCM

bool AudioPresent(double now) {
    return (now - g_inputs.audioLevelTime.load()) < 1.0 && g_inputs.audioLevel.load() > kAudioPresentLevel;
}

void OnSwitchRequested(bool isHardCut, void*) {
    g_engine.switchRequested = true;
    g_engine.switchHardCut = isHardCut;
}

void OnSwitchFailed(const char* filename, const char* message, void*) {
    LOGW("Preset load failed (%s): %s", filename ? filename : "", message ? message : "");
    g_engine.loadFailed = true;
}

void ApplySettings() {
    projectm_handle pm = g_engine.pm;
    projectm_set_preset_duration(pm, g_inputs.presetDuration.load());
    projectm_set_soft_cut_duration(pm, g_inputs.softCutDuration.load());
    projectm_set_preset_locked(pm, !g_inputs.autoChange.load());
    int meshWidth = g_inputs.meshWidth.load();
    int meshHeight = g_inputs.meshHeight.load();
    if (meshWidth != g_engine.appliedMeshWidth || meshHeight != g_engine.appliedMeshHeight) {
        // Only on real changes: a new mesh size rebuilds the per-vertex grid.
        projectm_set_mesh_size(pm, meshWidth, meshHeight);
        g_engine.appliedMeshWidth = meshWidth;
        g_engine.appliedMeshHeight = meshHeight;
    }
}

void Publish(const std::string& name) {
    {
        std::lock_guard<std::mutex> lock(g_published.mutex);
        g_published.currentPreset = name;
    }
    g_published.changeCounter.fetch_add(1);
}

// System-wide available memory (MemAvailable) in kB, or -1.
long AvailableMemoryKb() {
    FILE* f = fopen("/proc/meminfo", "r");
    if (!f) return -1;
    char line[128];
    long kb = -1;
    while (fgets(line, sizeof(line), f)) {
        if (sscanf(line, "MemAvailable: %ld kB", &kb) == 1) break;
    }
    fclose(f);
    return kb;
}

// Resident memory of this process in kB, or -1.
long ResidentMemoryKb() {
    FILE* f = fopen("/proc/self/statm", "r");
    if (!f) return -1;
    long size = 0, resident = -1;
    if (fscanf(f, "%ld %ld", &size, &resident) != 2) resident = -1;
    fclose(f);
    return resident < 0 ? -1 : resident * (sysconf(_SC_PAGESIZE) / 1024);
}

// A preset's warp and composite shader code as tools/gen-preset-index.py reads it: the "warp_N=" and
// "comp_N=" lines without leading backticks, joined with newlines, /* */ and then // comments removed.
std::string ShaderCode(const std::string& preset) {
    std::string code;
    bool first = true;
    size_t pos = 0;
    while (pos < preset.size()) {
        size_t end = preset.find('\n', pos);
        if (end == std::string::npos) end = preset.size();
        size_t lineEnd = end > pos && preset[end - 1] == '\r' ? end - 1 : end;
        if (preset.compare(pos, 5, "warp_") == 0 || preset.compare(pos, 5, "comp_") == 0) {
            size_t eq = pos + 5;
            while (eq < lineEnd && isdigit(static_cast<unsigned char>(preset[eq]))) ++eq;
            if (eq > pos + 5 && eq < lineEnd && preset[eq] == '=') {
                size_t start = eq + 1;
                while (start < lineEnd && preset[start] == '`') ++start;
                if (!first) code += '\n';
                code.append(preset, start, lineEnd - start);
                first = false;
            }
        }
        pos = end + 1;
    }
    std::string withoutBlocks;
    for (size_t i = 0; i < code.size();) {
        size_t open = code.find("/*", i);
        size_t close = open == std::string::npos ? open : code.find("*/", open + 2);
        if (close == std::string::npos) {  // no (complete) block comment left
            withoutBlocks.append(code, i, std::string::npos);
            break;
        }
        withoutBlocks.append(code, i, open - i);
        i = close + 2;
    }
    std::string result;
    for (size_t i = 0; i < withoutBlocks.size();) {
        size_t comment = withoutBlocks.find("//", i);
        if (comment == std::string::npos) {
            result.append(withoutBlocks, i, std::string::npos);
            break;
        }
        result.append(withoutBlocks, i, comment - i);
        i = withoutBlocks.find('\n', comment);
        if (i == std::string::npos) break;
    }
    return result;
}

// Size of a preset's warp and composite shader code (bytes, without comments) and its number of
// for-loops: the suspected drivers of GPU compile memory, logged next to the measured memory.
// Counted like tools/gen-preset-index.py, so the log matches the weights in presets.idx.
void ShaderStats(const std::string& preset, size_t& bytes, int& loops) {
    std::string code = ShaderCode(preset);
    bytes = code.size();
    loops = 0;
    for (size_t f = code.find("for"); f != std::string::npos; f = code.find("for", f + 3)) {
        size_t after = f + 3;
        while (after < code.size() && isspace(static_cast<unsigned char>(code[after]))) ++after;
        bool word = f == 0 || !(isalnum(static_cast<unsigned char>(code[f - 1])) || code[f - 1] == '_');
        if (word && after < code.size() && code[after] == '(') ++loops;
    }
}

bool UseLightweight() {
    int mode = g_inputs.transitionMode.load();
    return mode == kTransitionLightweight || (mode == kTransitionAuto && g_inputs.autoLightweight.load());
}

// Loads one preset; returns false if it could not be loaded (and marks it as skipped).
bool LoadPreset(const std::string& name, bool smooth) {
    std::string data = g_library.Load(name);
    if (data.empty()) {
        g_library.MarkSkipped(name, "unreadable or empty");
        return false;
    }
    g_engine.loading = name;
    g_engine.loadFailed = false;
    g_engine.inTransition = false;
    size_t shaderBytes = 0;
    int shaderLoops = 0;
    ShaderStats(data, shaderBytes, shaderLoops);
    long availBefore = AvailableMemoryKb();
    long rssBefore = ResidentMemoryKb();
    double loadStart = NowSeconds();
    // Parses the preset, loads its textures and compiles its shaders: the stall at a switch.
    projectm_load_preset_data(g_engine.pm, data.c_str(), smooth);
    double loadEnd = NowSeconds();
    double loadMs = (loadEnd - loadStart) * 1000.0;
    long availAfter = AvailableMemoryKb();
    long rssAfter = ResidentMemoryKb();
    // Memory the load took, to find the presets that cause memory peaks and calibrate their
    // weights: the drop in the system's available memory also covers GPU driver allocations.
    LOGI("LOAD preset='%s' ms=%.0f smooth=%d size=%dx%d weight_mb=%d shader_kb=%.1f loops=%d "
         "avail_drop_mb=%ld rss_growth_mb=%ld",
         name.c_str(), loadMs, smooth ? 1 : 0, g_engine.width, g_engine.height, g_library.Weight(name),
         shaderBytes / 1024.0, shaderLoops,
         availBefore >= 0 && availAfter >= 0 ? (availBefore - availAfter) / 1024 : 0,
         rssBefore >= 0 && rssAfter >= 0 ? (rssAfter - rssBefore) / 1024 : 0);
    if (g_engine.loadFailed) {
        g_library.MarkSkipped(name, "failed to load/compile");
        g_engine.loadFailed = false;
        return false;
    }
    g_engine.current = name;
    g_library.RecordShown(name);
    Publish(name);
    g_engine.lastLoadStart = loadStart;
    g_engine.lastLoadEnd = loadEnd;
    g_engine.lastLoadMs = loadMs;
    g_engine.detector.Arm(loadEnd, 2.0, name);
    return true;
}

// Measures the transition that follows the last load (see TrackTransition).
void BeginTransition(double seconds, bool lightweight) {
    g_engine.inTransition = true;
    g_engine.transitionLightweight = lightweight;
    g_engine.transitionStart = g_engine.lastLoadStart;
    g_engine.transitionLoadEnd = g_engine.lastLoadEnd;
    g_engine.transitionEnd = g_engine.lastLoadEnd + seconds;
    g_engine.transitionFrames = 0;
    g_engine.transitionSlowFrames = 0;
    g_engine.transitionWorstMs = g_engine.lastLoadMs;
    g_engine.fpsBeforeTransition = g_engine.lastFps;
    g_engine.detector.Arm(g_engine.lastLoadEnd, seconds + 2.0, g_engine.current);  // judge it after the blend
}

// Switches using the given selector, retrying a few times when presets fail to load.
template <typename Selector>
bool SwitchPreset(Selector select, bool smooth) {
    for (int attempt = 0; attempt < kMaxLoadAttemptsPerFrame; ++attempt) {
        std::string name = select();
        if (name.empty()) return false;
        if (LoadPreset(name, smooth)) return true;
    }
    return false;
}

// Selector that tries `first` (if non-empty) and falls back to the shuffled order.
std::function<std::string()> FirstThenNext(std::string first) {
    return [first = std::move(first)]() mutable {
        if (!first.empty()) return std::exchange(first, std::string());
        return g_library.Next();
    };
}

// Automatic switch requested by projectM (preset time is up, or a hard cut on a loud beat).
void HandleAutoSwitch() {
    g_engine.switchRequested = false;
    bool hardCut = g_engine.switchHardCut || g_inputs.forceHardCut.exchange(false);
    int softCut = g_inputs.softCutDuration.load();
    bool lightweight = !hardCut && softCut > 0 && g_engine.snapshotReady && UseLightweight();
    bool smooth = !hardCut && !lightweight;
    if (!lightweight) g_engine.fade.Stop();
    if (!SwitchPreset([] { return g_library.Next(); }, smooth)) {
        g_engine.fade.Stop();
        return;
    }
    if (lightweight) {
        double seconds = std::min<double>(softCut, kMaxLightweightSeconds);
        g_engine.fade.Start(NowSeconds(), seconds);
        BeginTransition(seconds, true);
    } else if (smooth && softCut > 0) {
        BeginTransition(softCut, false);
    }
}

void HandleCommands() {
    int command = g_inputs.command.exchange(kNone);
    if (command != kNone) {
        bool smooth = !g_inputs.commandHardCut.load();
        g_engine.fade.Stop();  // remote-control switches are immediate
        switch (command) {
            case kNext:
                SwitchPreset([] { return g_library.Next(); }, smooth);
                break;
            case kRandom:
                SwitchPreset([] { return g_library.Random(g_engine.current); }, smooth);
                break;
            case kSkipCurrent:
                g_library.MarkSkipped(g_engine.current, "too slow on this device");
                SwitchPreset([] { return g_library.Next(); }, false);
                break;
            case kPrevious: {
                std::string previous = g_library.Previous();
                if (!previous.empty()) SwitchPreset(FirstThenNext(previous), smooth);
                break;
            }
            default:
                break;
        }
        g_engine.switchRequested = false;
    } else if (g_engine.switchRequested) {
        HandleAutoSwitch();
    }
    g_engine.snapshotReady = false;
}

// Called after a frame is complete: if projectM asked for a switch that will be a lightweight
// transition, keep a copy of this (outgoing) frame for the fade.
void CaptureOutgoingFrame() {
    if (g_engine.snapshotReady || !g_engine.switchRequested || g_engine.switchHardCut) return;
    if (g_inputs.forceHardCut.load() || g_inputs.softCutDuration.load() <= 0 || !UseLightweight()) return;
    if (g_inputs.command.load() != kNone) return;  // a remote-control switch comes first
    g_engine.snapshotReady = g_engine.fade.Capture(g_engine.width, g_engine.height);
}

void FeedAudio() {
    {
        std::lock_guard<std::mutex> lock(g_inputs.pcmMutex);
        g_engine.pcmScratch.swap(g_inputs.pcm);
        g_inputs.pcm.clear();
    }
    auto& pcm = g_engine.pcmScratch;
    if (pcm.empty()) return;
    size_t maxSamples = projectm_pcm_get_max_samples();
    size_t offset = pcm.size() > maxSamples ? pcm.size() - maxSamples : 0;
    projectm_pcm_add_uint8(g_engine.pm, pcm.data() + offset,
                           static_cast<unsigned int>(pcm.size() - offset), PROJECTM_MONO);
    pcm.clear();
}

void UpdateFps(double now) {
    ++g_engine.framesSinceFps;
    double elapsed = now - g_engine.fpsWindowStart;
    if (elapsed >= 1.0) {
        g_engine.lastFps = static_cast<float>(g_engine.framesSinceFps / elapsed);
        projectm_set_fps(g_engine.pm, static_cast<int32_t>(g_engine.lastFps + 0.5f));
        g_engine.framesSinceFps = 0;
        g_engine.fpsWindowStart = now;
    }
}

// Frame-time statistics for the running transition; logged and published when it ends. In Auto
// mode a classic blend that runs clearly slower than the frames before it switches to lightweight.
void TrackTransition(double now) {
    double frameMs = g_engine.lastFrameAt > 0 ? (now - g_engine.lastFrameAt) * 1000.0 : 0;
    g_engine.lastFrameAt = now;
    if (!g_engine.inTransition) return;
    ++g_engine.transitionFrames;
    if (frameMs > 50.0) ++g_engine.transitionSlowFrames;  // below 20 fps: a visible stutter
    g_engine.transitionWorstMs = std::max(g_engine.transitionWorstMs, frameMs);
    if (now < g_engine.transitionEnd) return;
    g_engine.inTransition = false;
    float fps = static_cast<float>(g_engine.transitionFrames / std::max(0.001, now - g_engine.transitionStart));
    float blendFps = static_cast<float>(g_engine.transitionFrames / std::max(0.001, now - g_engine.transitionLoadEnd));
    bool lightweight = g_engine.transitionLightweight;
    LOGI("TRANSITION preset='%s' mode=%s load_ms=%.0f fps=%.1f blend_fps=%.1f before_fps=%.1f frames=%d "
         "slow_frames=%d worst_ms=%.0f",
         g_engine.current.c_str(), lightweight ? "lightweight" : "classic", g_engine.lastLoadMs, fps, blendFps,
         g_engine.fpsBeforeTransition, g_engine.transitionFrames, g_engine.transitionSlowFrames,
         g_engine.transitionWorstMs);
    g_published.lastTransitionFps = fps;
    g_published.transitionCounter.fetch_add(1);
    float before = g_engine.fpsBeforeTransition;
    if (!lightweight && g_inputs.transitionMode.load() == kTransitionAuto && !g_inputs.autoLightweight.load() &&
        before > 0 && blendFps < before * kSlowBlendRatio) {
        g_inputs.autoLightweight = true;
        LOGI("TRANSITION auto: classic blend ran at %.1f fps (%.1f before), using lightweight transitions",
             blendFps, before);
    }
}

// contextAlive: the EGL context that owns our GL objects is still current (else just forget them).
void DestroyEngineLocked(bool contextAlive) {
    if (contextAlive) {
        g_engine.fade.Release();
        g_engine.detector.Release();
    } else {
        g_engine.fade.Forget();
        g_engine.detector.Forget();
    }
    g_engine.snapshotReady = false;
    if (g_engine.pm) {
        projectm_destroy(g_engine.pm);
        g_engine.pm = nullptr;
    }
    g_engine.width = g_engine.height = 0;
    g_engine.appliedMeshWidth = g_engine.appliedMeshHeight = 0;
    g_engine.texturesApplied = false;
    g_engine.inTransition = false;
    g_engine.lastFrameAt = 0;
    g_engine.current.clear();  // the next instance resumes from g_published.currentPreset
    g_engine.switchRequested = false;
    g_engine.detector.Disarm();
}

}  // namespace

#define JNI_FN(name) Java_com_example_projectm_visualizer_ProjectMJNI_##name

extern "C" {

JNIEXPORT void JNICALL JNI_FN(init)(JNIEnv* env, jclass, jobject assetManager, jstring skipFile,
                                    jstring textureDir) {
    if (!g_assetManagerRef) g_assetManagerRef = env->NewGlobalRef(assetManager);
    AAssetManager* assets = AAssetManager_fromJava(env, g_assetManagerRef);
    const char* path = env->GetStringUTFChars(skipFile, nullptr);
    const char* textures = env->GetStringUTFChars(textureDir, nullptr);
    g_library.Start(assets, path, textures);
    env->ReleaseStringUTFChars(skipFile, path);
    env->ReleaseStringUTFChars(textureDir, textures);
}

// Recent audio level (RMS of normalized samples, 0..1); 0 when no audio arrived for 1 s.
JNIEXPORT jfloat JNICALL JNI_FN(getAudioLevel)(JNIEnv*, jclass) {
    return (NowSeconds() - g_inputs.audioLevelTime.load()) < 1.0 ? g_inputs.audioLevel.load() : 0.f;
}

JNIEXPORT void JNICALL JNI_FN(onSurfaceCreated)(JNIEnv*, jclass) {
    std::lock_guard<std::mutex> lock(g_engineMutex);
    // A new EGL context invalidates all GL objects of a previous instance.
    DestroyEngineLocked(false);
    g_engine.pm = projectm_create();
    if (!g_engine.pm) {
        LOGE("projectm_create failed");
        return;
    }
    projectm_set_hard_cut_enabled(g_engine.pm, true);
    projectm_set_beat_sensitivity(g_engine.pm, 1.0f);
    projectm_set_preset_switch_requested_event_callback(g_engine.pm, OnSwitchRequested, nullptr);
    projectm_set_preset_switch_failed_event_callback(g_engine.pm, OnSwitchFailed, nullptr);
    g_inputs.settingsDirty = true;
    g_engine.fpsWindowStart = NowSeconds();
    g_engine.createdAt = g_engine.fpsWindowStart;
    g_engine.firstPresetLogged = false;
    LOGI("projectM instance created");
}

JNIEXPORT void JNICALL JNI_FN(onSurfaceChanged)(JNIEnv*, jclass, jint width, jint height) {
    std::lock_guard<std::mutex> lock(g_engineMutex);
    if (!g_engine.pm) return;
    if (width != g_engine.width || height != g_engine.height) {
        // Resets projectM's renderer, so only call it on real size changes.
        projectm_set_window_size(g_engine.pm, width, height);
        g_engine.width = width;
        g_engine.height = height;
        LOGI("Render size %dx%d", width, height);
    }
    glViewport(0, 0, width, height);
}

JNIEXPORT void JNICALL JNI_FN(onDrawFrame)(JNIEnv*, jclass) {
    std::lock_guard<std::mutex> lock(g_engineMutex);
    if (!g_engine.pm) return;
    double now = NowSeconds();

    if (g_inputs.settingsDirty.exchange(false)) ApplySettings();

    if (g_engine.loadFailed) {  // failure reported outside of a load call
        g_library.MarkSkipped(g_engine.loading, "failed to load/compile");
        g_engine.loadFailed = false;
    }

    if (g_engine.current.empty()) {
        // First frame(s): show the idle preset until the index is ready, then start immediately.
        if (g_library.Ready()) {
            if (!g_engine.texturesApplied) {
                // Once, before the first preset: this call rescans and reloads all textures.
                const char* paths[] = {g_library.TextureDir().c_str()};
                if (!g_library.TextureDir().empty()) projectm_set_texture_search_paths(g_engine.pm, paths, 1);
                g_engine.texturesApplied = true;
            }
            std::string resume;  // preset shown before an EGL context loss, if any
            {
                std::lock_guard<std::mutex> published(g_published.mutex);
                resume = g_published.currentPreset;
            }
            SwitchPreset(FirstThenNext(resume), false);
        }
    } else {
        HandleCommands();
    }

    FeedAudio();
    projectm_opengl_render_frame(g_engine.pm);

    if (!g_engine.firstPresetLogged && !g_engine.current.empty()) {
        // Logged after the first frame of the first preset has been rendered.
        g_engine.firstPresetLogged = true;
        LOGI("STARTUP first preset rendered %.0f ms after engine creation",
             (NowSeconds() - g_engine.createdAt) * 1000.0);
    }

    // Reads the preset's own output, so it runs before the transition overlay is drawn.
    const char* blank = g_engine.detector.Update(now, g_engine.width, g_engine.height, AudioPresent(now));
    if (g_engine.detector.TakeVisible()) g_engine.blankInARow = 0;
    if (blank && g_inputs.blankDetection.load() && ++g_engine.blankInARow > kMaxBlankInARow) {
        if (g_engine.blankInARow == kMaxBlankInARow + 1) {
            LOGW("BLANK %d presets in a row rendered black: suspecting a rendering problem, not skipping "
                 "until a preset shows output", kMaxBlankInARow);
        }
    } else if (blank && g_inputs.blankDetection.load()) {
        int strikes = g_library.AddBlankStrike(g_engine.current);
        if (strikes >= kBlankStrikesToSkip) {
            g_library.MarkSkipped(g_engine.current, "renders no visible output (twice)");
        } else {
            LOGW("BLANK preset='%s' strike=%d: moving on", g_engine.current.c_str(), strikes);
        }
        g_engine.fade.Stop();
        SwitchPreset([] { return g_library.Next(); }, false);
    }
    double end = NowSeconds();
    g_engine.fade.Draw(end);
    CaptureOutgoingFrame();
    TrackTransition(end);
    UpdateFps(now);
}

JNIEXPORT void JNICALL JNI_FN(release)(JNIEnv*, jclass) {
    std::lock_guard<std::mutex> lock(g_engineMutex);
    DestroyEngineLocked(true);
}

JNIEXPORT void JNICALL JNI_FN(addWaveform)(JNIEnv* env, jclass, jbyteArray waveform, jint length) {
    if (length <= 0) return;
    std::lock_guard<std::mutex> lock(g_inputs.pcmMutex);
    auto& pcm = g_inputs.pcm;
    size_t oldSize = pcm.size();
    pcm.resize(oldSize + length);
    env->GetByteArrayRegion(waveform, 0, length, reinterpret_cast<jbyte*>(pcm.data() + oldSize));

    // RMS of the 8-bit unsigned samples (128 = silence) used to gate black-frame detection.
    double sum = 0;
    for (size_t i = oldSize; i < pcm.size(); ++i) {
        double s = (static_cast<int>(pcm[i]) - 128) / 128.0;
        sum += s * s;
    }
    g_inputs.audioLevel = static_cast<float>(std::sqrt(sum / length));
    g_inputs.audioLevelTime = NowSeconds();

    constexpr size_t kMaxPending = 8192;  // never let the buffer grow while rendering is paused
    if (pcm.size() > kMaxPending) pcm.erase(pcm.begin(), pcm.end() - kMaxPending);
}

JNIEXPORT void JNICALL JNI_FN(nextPreset)(JNIEnv*, jclass, jboolean hardCut) {
    g_inputs.commandHardCut = hardCut;
    g_inputs.command = kNext;
}

JNIEXPORT void JNICALL JNI_FN(previousPreset)(JNIEnv*, jclass, jboolean hardCut) {
    g_inputs.commandHardCut = hardCut;
    g_inputs.command = kPrevious;
}

JNIEXPORT void JNICALL JNI_FN(randomPreset)(JNIEnv*, jclass, jboolean hardCut) {
    g_inputs.commandHardCut = hardCut;
    g_inputs.command = kRandom;
}

JNIEXPORT void JNICALL JNI_FN(setPresetDuration)(JNIEnv*, jclass, jint seconds) {
    g_inputs.presetDuration = std::max(1, static_cast<int>(seconds));
    g_inputs.settingsDirty = true;
}

JNIEXPORT void JNICALL JNI_FN(setSoftCutDuration)(JNIEnv*, jclass, jint seconds) {
    g_inputs.softCutDuration = std::max(0, static_cast<int>(seconds));
    g_inputs.settingsDirty = true;
}

JNIEXPORT void JNICALL JNI_FN(setAutoChange)(JNIEnv*, jclass, jboolean enabled) {
    g_inputs.autoChange = enabled;
    g_inputs.settingsDirty = true;
}

JNIEXPORT void JNICALL JNI_FN(setMeshSize)(JNIEnv*, jclass, jint width, jint height) {
    g_inputs.meshWidth = width;
    g_inputs.meshHeight = height;
    g_inputs.settingsDirty = true;
}

JNIEXPORT void JNICALL JNI_FN(skipCurrentPreset)(JNIEnv*, jclass) {
    g_inputs.command = kSkipCurrent;
}

JNIEXPORT void JNICALL JNI_FN(setBlankDetection)(JNIEnv*, jclass, jboolean enabled) {
    g_inputs.blankDetection = enabled;
}

JNIEXPORT void JNICALL JNI_FN(setTransitionMode)(JNIEnv*, jclass, jint mode, jboolean autoStartsLightweight) {
    g_inputs.transitionMode = std::clamp(static_cast<int>(mode), 0, 2);
    g_inputs.autoLightweight = autoStartsLightweight;
}

// True when automatic switches currently use the lightweight transition.
JNIEXPORT jboolean JNICALL JNI_FN(isLightweightTransition)(JNIEnv*, jclass) {
    return UseLightweight();
}

JNIEXPORT void JNICALL JNI_FN(setForceHardCut)(JNIEnv*, jclass, jboolean enabled) {
    g_inputs.forceHardCut = enabled;
}

JNIEXPORT jstring JNICALL JNI_FN(getSystemProperty)(JNIEnv* env, jclass, jstring name) {
    const char* key = env->GetStringUTFChars(name, nullptr);
    char value[PROP_VALUE_MAX] = {0};
    __system_property_get(key, value);
    env->ReleaseStringUTFChars(name, key);
    return env->NewStringUTF(value);
}

JNIEXPORT jstring JNICALL JNI_FN(getCurrentPresetName)(JNIEnv* env, jclass) {
    std::lock_guard<std::mutex> lock(g_published.mutex);
    return env->NewStringUTF(g_published.currentPreset.c_str());
}

JNIEXPORT jint JNICALL JNI_FN(getTransitionCounter)(JNIEnv*, jclass) {
    return g_published.transitionCounter.load();
}

JNIEXPORT jfloat JNICALL JNI_FN(getLastTransitionFps)(JNIEnv*, jclass) {
    return g_published.lastTransitionFps.load();
}

JNIEXPORT jint JNICALL JNI_FN(getPresetChangeCounter)(JNIEnv*, jclass) {
    return g_published.changeCounter.load();
}

JNIEXPORT jint JNICALL JNI_FN(getPresetCount)(JNIEnv*, jclass) {
    return g_library.ActiveCount();
}

JNIEXPORT jint JNICALL JNI_FN(getSkippedCount)(JNIEnv*, jclass) {
    return g_library.SkippedCount();
}

JNIEXPORT void JNICALL JNI_FN(resetSkippedPresets)(JNIEnv*, jclass) {
    g_library.ResetSkipped();
}

JNIEXPORT jstring JNICALL JNI_FN(getVersion)(JNIEnv* env, jclass) {
    char* version = projectm_get_version_string();
    jstring result = env->NewStringUTF(version ? version : "unknown");
    if (version) projectm_free_string(version);
    return result;
}

}  // extern "C"
