name: User guide

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docs-build.yml

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/pages-deploy.yml
